// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QrCodeCourses;

namespace QrCodeCourses.Migrations
{
    [DbContext(typeof(QRCodePanier))]
    partial class QRCodePanierModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("QrCodeCourses.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PanierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArticleId");

                    b.HasIndex("PanierId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("QrCodeCourses.Panier", b =>
                {
                    b.Property<int>("PanierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("PanierId");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("QrCodeCourses.Article", b =>
                {
                    b.HasOne("QrCodeCourses.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("PanierId");
                });
#pragma warning restore 612, 618
        }
    }
}
